-- =============================================================
-- ATS — Aniruddha Telemetry System
-- PostgreSQL Schema
-- =============================================================

-- =============================================================
-- SHARED TRIGGER FUNCTION
-- =============================================================
CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- CROSS-TENANT VALIDATION TRIGGER
-- Validates that project, expense_type, and submitting employee
-- all belong to the exact same organization_id as the expense.
-- =============================================================
CREATE OR REPLACE FUNCTION validate_expense_org_consistency()
RETURNS TRIGGER AS $$
DECLARE
    v_project_org_id      INT;
    v_expense_type_org_id INT;
BEGIN
    -- 1. Validate Employee Membership
    IF NOT EXISTS (
        SELECT 1 FROM memberships 
        WHERE employee_id = NEW.employee_id 
          AND organization_id = NEW.organization_id
    ) THEN
        RAISE EXCEPTION 
            'Cross-tenant violation: employee % is not an active member of org %', 
            NEW.employee_id, NEW.organization_id;
    END IF;

    -- 2. Validate Project Organization
    SELECT b.organization_id INTO v_project_org_id
    FROM projects p
    JOIN budgets b ON b.budget_id = p.budget_id
    WHERE p.project_id = NEW.project_id;

    IF v_project_org_id IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION
            'Cross-tenant violation: project % belongs to org % but expense is for org %',
            NEW.project_id, v_project_org_id, NEW.organization_id;
    END IF;

    -- 3. Validate Expense Type Organization
    SELECT organization_id INTO v_expense_type_org_id
    FROM expense_types
    WHERE expense_type_id = NEW.expense_type_id;

    IF v_expense_type_org_id IS DISTINCT FROM NEW.organization_id THEN
        RAISE EXCEPTION
            'Cross-tenant violation: expense_type % belongs to org % but expense is for org %',
            NEW.expense_type_id, v_expense_type_org_id, NEW.organization_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================
-- ORGANIZATIONS
-- =============================================================
CREATE TABLE organizations (
    organization_id INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    slug            VARCHAR(100)    NOT NULL UNIQUE,
    description     TEXT,
    is_system       BOOLEAN         NOT NULL DEFAULT FALSE,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER set_updated_at_organizations
    BEFORE UPDATE ON organizations
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================
-- USERS
-- =============================================================
CREATE TABLE users (
    employee_id     INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    email           VARCHAR(254)    NOT NULL UNIQUE,
    password_hash   TEXT            NOT NULL,
    account_status  VARCHAR(20)     NOT NULL DEFAULT 'active'
                    CHECK (account_status IN ('active', 'suspended', 'locked', 'inactive')),
    is_superuser    BOOLEAN         NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER set_updated_at_users
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================
-- EMPLOYEE_STATUS
-- Temporal status log with strict single-active record constraint
-- =============================================================
CREATE TABLE employee_status (
    status_id       INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    status          VARCHAR(20)     NOT NULL
                    CHECK (status IN ('active', 'inactive', 'suspended', 'on_leave')),
    started_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at        TIMESTAMP,
    updated_by      INT
                    REFERENCES users(employee_id) ON DELETE SET NULL,
    CONSTRAINT chk_status_dates CHECK (ended_at IS NULL OR ended_at > started_at)
);

CREATE INDEX idx_employee_status_employee ON employee_status(employee_id);
CREATE UNIQUE INDEX idx_employee_status_single_active 
    ON employee_status(employee_id) WHERE ended_at IS NULL;

-- =============================================================
-- MEMBERSHIPS
-- =============================================================
CREATE TABLE memberships (
    membership_id   INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE CASCADE,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE CASCADE,
    is_admin        BOOLEAN         NOT NULL DEFAULT FALSE,
    joined_at       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, organization_id)
);

CREATE TRIGGER set_updated_at_memberships
    BEFORE UPDATE ON memberships
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_memberships_employee ON memberships(employee_id);
CREATE INDEX idx_memberships_org      ON memberships(organization_id);

-- =============================================================
-- ROLES
-- =============================================================
CREATE TABLE roles (
    role_id         INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, organization_id)
);

CREATE TRIGGER set_updated_at_roles
    BEFORE UPDATE ON roles
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_roles_org ON roles(organization_id);

-- =============================================================
-- PERMISSIONS
-- =============================================================
CREATE TABLE permissions (
    permission_id   INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name        VARCHAR(100)    NOT NULL,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    is_global       BOOLEAN         NOT NULL DEFAULT FALSE,
    description     TEXT,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (api_name, organization_id)
);

CREATE TRIGGER set_updated_at_permissions
    BEFORE UPDATE ON permissions
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_permissions_org ON permissions(organization_id);

-- =============================================================
-- MEMBERSHIP_ROLES
-- =============================================================
CREATE TABLE membership_roles (
    membership_id   INT             NOT NULL
                    REFERENCES memberships(membership_id) ON DELETE CASCADE,
    role_id         INT             NOT NULL
                    REFERENCES roles(role_id) ON DELETE RESTRICT,
    PRIMARY KEY (membership_id, role_id)
);

-- =============================================================
-- ROLE_PERMISSIONS
-- =============================================================
CREATE TABLE role_permissions (
    role_id         INT             NOT NULL
                    REFERENCES roles(role_id) ON DELETE CASCADE,
    permission_id   INT             NOT NULL
                    REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- =============================================================
-- USER_PERMISSIONS
-- =============================================================
CREATE TABLE user_permissions (
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE CASCADE,
    permission_id   INT             NOT NULL
                    REFERENCES permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, permission_id)
);

-- =============================================================
-- CATEGORIES
-- =============================================================
CREATE TABLE categories (
    category_id     INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, organization_id)
);

CREATE TRIGGER set_updated_at_categories
    BEFORE UPDATE ON categories
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================
-- EXPENSE_TYPES
-- =============================================================
CREATE TABLE expense_types (
    expense_type_id INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100)    NOT NULL,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    requires_receipt BOOLEAN        NOT NULL DEFAULT FALSE,
    default_limit   DECIMAL(15, 2)  CHECK (default_limit IS NULL OR default_limit > 0),
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (name, organization_id)
);

CREATE TRIGGER set_updated_at_expense_types
    BEFORE UPDATE ON expense_types
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

-- =============================================================
-- BUDGETS
-- =============================================================
CREATE TABLE budgets (
    budget_id       INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount          DECIMAL(15, 2)  NOT NULL CHECK (amount > 0),
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    start_date      DATE            NOT NULL,
    end_date        DATE            NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_budget_dates CHECK (end_date > start_date)
);

CREATE TRIGGER set_updated_at_budgets
    BEFORE UPDATE ON budgets
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_budgets_org ON budgets(organization_id);

-- =============================================================
-- PROJECTS
-- =============================================================
CREATE TABLE projects (
    project_id      INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id       INT             NOT NULL
                    REFERENCES budgets(budget_id) ON DELETE RESTRICT,
    name            VARCHAR(150)    NOT NULL,
    description     TEXT,
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    start_date      DATE,
    end_date        DATE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_project_dates CHECK (end_date IS NULL OR end_date > start_date)
);

CREATE TRIGGER set_updated_at_projects
    BEFORE UPDATE ON projects
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_projects_budget     ON projects(budget_id);
CREATE INDEX idx_projects_date_range ON projects(start_date, end_date);

-- =============================================================
-- PROJECT_CATEGORIES
-- =============================================================
CREATE TABLE project_categories (
    project_category_id INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INT             NOT NULL
                    REFERENCES projects(project_id) ON DELETE CASCADE,
    category_id     INT             NOT NULL
                    REFERENCES categories(category_id) ON DELETE RESTRICT,
    UNIQUE (project_id, category_id)
);

-- =============================================================
-- PROJECT_MEMBERS
-- =============================================================
CREATE TABLE project_members (
    project_member_id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      INT             NOT NULL
                    REFERENCES projects(project_id) ON DELETE RESTRICT,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    role_id         INT             NOT NULL
                    REFERENCES roles(role_id) ON DELETE RESTRICT,
    UNIQUE (project_id, employee_id)
);

CREATE INDEX idx_project_members_project  ON project_members(project_id);
CREATE INDEX idx_project_members_employee ON project_members(employee_id);

-- =============================================================
-- EXPENSES
-- =============================================================
CREATE TABLE expenses (
    expense_id      INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    project_id      INT             NOT NULL
                    REFERENCES projects(project_id) ON DELETE RESTRICT,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    expense_type_id INT             NOT NULL
                    REFERENCES expense_types(expense_type_id) ON DELETE RESTRICT,
    amount          DECIMAL(15, 2)  NOT NULL CHECK (amount > 0),
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'rejected', 'reimbursed')),
    rejection_reason VARCHAR(255),
    expense_date    DATE            NOT NULL,
    submission_date TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_rejection_reason
        CHECK (status != 'rejected' OR rejection_reason IS NOT NULL)
);

CREATE TRIGGER set_updated_at_expenses
    BEFORE UPDATE ON expenses
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER validate_expense_org
    BEFORE INSERT OR UPDATE ON expenses
    FOR EACH ROW EXECUTE FUNCTION validate_expense_org_consistency();

CREATE INDEX idx_expenses_employee ON expenses(employee_id);
CREATE INDEX idx_expenses_project  ON expenses(project_id);
CREATE INDEX idx_expenses_org      ON expenses(organization_id);
CREATE INDEX idx_expenses_status   ON expenses(status);
CREATE INDEX idx_expenses_type     ON expenses(expense_type_id);

-- =============================================================
-- EXPENSE_APPROVALS
-- =============================================================
CREATE TABLE expense_approvals (
    approval_id     INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      INT             NOT NULL
                    REFERENCES expenses(expense_id) ON DELETE RESTRICT,
    actioned_by     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    action          VARCHAR(20)     NOT NULL
                    CHECK (action IN ('approved', 'rejected')),
    comments        TEXT,
    actioned_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_expense_approvals_expense     ON expense_approvals(expense_id);
CREATE INDEX idx_expense_approvals_actioned_by ON expense_approvals(actioned_by);

-- =============================================================
-- EXPENSE_MEDIA
-- =============================================================
CREATE TABLE expense_media (
    media_id        INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      INT             NOT NULL
                    REFERENCES expenses(expense_id) ON DELETE CASCADE,
    receipt_url     VARCHAR(512)    NOT NULL,
    description     TEXT,
    uploaded_at     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_expense_media_expense ON expense_media(expense_id);

-- =============================================================
-- REIMBURSEMENTS
-- =============================================================
CREATE TABLE reimbursements (
    reimbursement_id INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id      INT             NOT NULL UNIQUE
                    REFERENCES expenses(expense_id) ON DELETE RESTRICT,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE RESTRICT,
    organization_id INT             NOT NULL
                    REFERENCES organizations(organization_id) ON DELETE RESTRICT,
    total_amount    DECIMAL(15, 2)  NOT NULL CHECK (total_amount > 0),
    payment_reference VARCHAR(100),
    status          VARCHAR(20)     NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'processing', 'paid', 'failed')),
    paid_at         TIMESTAMP,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_paid_atre
        CHECK (status != 'paid' OR paid_at IS NOT NULL)
);

CREATE TRIGGER set_updated_at_reimbursements
    BEFORE UPDATE ON reimbursements
    FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE INDEX idx_reimbursements_employee ON reimbursements(employee_id);
CREATE INDEX idx_reimbursements_org      ON reimbursements(organization_id);
CREATE INDEX idx_reimbursements_status   ON reimbursements(status);

-- =============================================================
-- AUDIT_LOGS
-- =============================================================
CREATE TABLE audit_logs (
    log_id          INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id        INT
                    REFERENCES users(employee_id) ON DELETE SET NULL,
    action          VARCHAR(50)     NOT NULL,
    table_name      VARCHAR(100)    NOT NULL,
    record_id       VARCHAR(50)     NOT NULL,
    old_values      JSONB,
    new_values      JSONB,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_audit_logs_actor      ON audit_logs(actor_id);
CREATE INDEX idx_audit_logs_table      ON audit_logs(table_name);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX idx_audit_logs_old_values ON audit_logs USING GIN (old_values);
CREATE INDEX idx_audit_logs_new_values ON audit_logs USING GIN (new_values);

-- =============================================================
-- AUTHENTICATION_TOKENS
-- =============================================================
CREATE TABLE authentication_tokens (
    token_id        INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE CASCADE,
    token_hash      TEXT            NOT NULL,
    purpose         VARCHAR(50)     NOT NULL
                    CHECK (purpose IN ('login', 'reset_password', 'refresh', 'verify_email')),
    expires_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- High-performance HASH index for token equality checks
CREATE INDEX idx_auth_tokens_hash             ON authentication_tokens USING HASH (token_hash);
CREATE INDEX idx_auth_tokens_expires_at      ON authentication_tokens(expires_at);
CREATE INDEX idx_auth_tokens_employee_purpose ON authentication_tokens(employee_id, purpose);

-- =============================================================
-- NOTIFICATIONS
-- =============================================================
CREATE TABLE notifications (
    notification_id INT             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     INT             NOT NULL
                    REFERENCES users(employee_id) ON DELETE CASCADE,
    title           VARCHAR(150)    NOT NULL,
    message         TEXT            NOT NULL,
    type            VARCHAR(50)     NOT NULL,
    reference_id    VARCHAR(50),
    is_read         BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_notifications_employee_read ON notifications(employee_id, is_read);