// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9AptVG8R9lNHZulr313-DN62WkFA2q4A',
    appId: '1:581115815178:web:887a0dda6a6a866d5746f3',
    messagingSenderId: '581115815178',
    projectId: 'ats-onework-332dc',
    authDomain: 'ats-onework-332dc.firebaseapp.com',
    storageBucket: 'ats-onework-332dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1k33h8aA3p-9FkosI-5V2boY5uPig_BM',
    appId: '1:581115815178:android:632b382d826124e25746f3',
    messagingSenderId: '581115815178',
    projectId: 'ats-onework-332dc',
    storageBucket: 'ats-onework-332dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGZpfzeS1S1x4_238iRH7XNRUGeQ_qDJ8',
    appId: '1:581115815178:ios:a3a0e849c9a9d3c65746f3',
    messagingSenderId: '581115815178',
    projectId: 'ats-onework-332dc',
    storageBucket: 'ats-onework-332dc.firebasestorage.app',
    iosBundleId: 'com.example.atsOnework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGZpfzeS1S1x4_238iRH7XNRUGeQ_qDJ8',
    appId: '1:581115815178:ios:a3a0e849c9a9d3c65746f3',
    messagingSenderId: '581115815178',
    projectId: 'ats-onework-332dc',
    storageBucket: 'ats-onework-332dc.firebasestorage.app',
    iosBundleId: 'com.example.atsOnework',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9AptVG8R9lNHZulr313-DN62WkFA2q4A',
    appId: '1:581115815178:web:2412a77b4a0cfd7d5746f3',
    messagingSenderId: '581115815178',
    projectId: 'ats-onework-332dc',
    authDomain: 'ats-onework-332dc.firebaseapp.com',
    storageBucket: 'ats-onework-332dc.firebasestorage.app',
  );
}
